import dayjs from "dayjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dayJsRelativeTimePlugin from "dayjs/plugin/relativeTime";
import Script from "next/script";

dayjs.extend(dayJsRelativeTimePlugin);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app"
};

export default function RootLayout({
 children
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <body className={inter.className}>
    {children}
    {/* https://ionic.io/ionicons/usage */}
    <Script
     type="module"
     src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></Script>
    <Script
     noModule
     src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></Script>
   </body>
  </html>
 );
}
